theme: jekyll-theme-minimal
title: blog.rickscherer.com
description: The personal blog of Rick Scherer.<BR>Dell EMC Principal Global Architect • Master Enterprise Architect • Trusted Adviser • VCDX-DCV • DECM-EA
logo: https://education.emc.com/content/emc/en-us/home/Master-Enterprise-Architect/_jcr_content/main_content/greybackground/grey_background/grid_copy/content-0-0/textimage/image.img.jpg/1518611411192.jpg
google_analytics: UA-6495038-3
