theme: jekyll-theme-minimal
title: blog.rickscherer.com
description: The personal blog of Rick Scherer.<BR>Dell EMC Principal Global Architect • Master Enterprise Architect • Trusted Adviser • VCDX-DCV • DECM-EA
logo: https://blog.rickscherer.com/rick.jpg
google_analytics: UA-6495038-3
